export const LIKE_IMAGE_REQUEST = 'LIKE_IMAGE_REQUEST'
export const LIKE_IMAGE_SUCCESS = 'LIKE_IMAGE_SUCCESS'
export const LIKE_IMAGE_FAIL = 'LIKE_IMAGE_FAIL'

export const UNLIKE_IMAGE_REQUEST = 'UNLIKE_IMAGE_REQUEST'
export const UNLIKE_IMAGE_SUCCESS = 'UNLIKE_IMAGE_SUCCESS'
export const UNLIKE_IMAGE_FAIL = 'UNLIKE_IMAGE_FAIL'