export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_UPDATE_ITEM = 'SEARCH_UPDATE_ITEM'

export const SEARCH_QUERY_ADD_NEW = 'SEARCH_QUERY_ADD_NEW'