export const USER_TOKEN_REQUEST = 'USER_TOKEN_REQUEST'
export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS'
export const USER_TOKEN_FAIL = 'USER_TOKEN_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_LIKES_REQUEST = 'USER_LIKES_REQUEST'
export const USER_LIKES_SUCCESS = 'USER_LIKES_SUCCESS'
export const USER_LIKES_FAIL = 'USER_LIKES_FAIL'
export const USER_LIKES_UPDATE = 'USER_LIKES_UPDATE'