export const USER_TOKEN_REQUEST = 'USER_TOKEN_REQUEST'
export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS'
export const USER_TOKEN_FAIL = 'USER_TOKEN_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'